Repository SoftwareEngineering-TermProject/IssueTrackingSystem_BACKEND, pull requests merged in 2024-05, with the labels that each got.

#23 [feat] #1 Issue - 이슈 생성 api
  src/main/java/com/example/IssueTrackingSystem/IssueTrackingSystemApplication.java
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/Issue.java
  src/main/java/com/example/IssueTrackingSystem/repository/IssueRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandService.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/IssueController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueRequestDTO.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueResponseDTO.java
Labels: feat

#28 [feat] #1 프로젝트 - 프로젝트 생성 시 admin이 아니면 예외 처리
  src/main/java/com/example/IssueTrackingSystem/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/IssueTrackingSystem/apiPayload/exception/handler/ProjectHandler.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandService.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/ProjectController.java
Labels: feat

#30 [refactor] 이슈를 작성한 유저와 admin만 이슈 생성, 수정, 삭제 가능하게 api 리팩토링
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandServiceImpl.java
Labels: refactor

#50 [feat] #2 issue - 이슈 생성 api requestBody에 priority 추가
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueRequestDTO.java
Labels: feat

#52 [refactor] 이슈 리스트 response에 userId, userName, 이슈 생성일, fixer, assignee 추가
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/Issue.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueResponseDTO.java
Labels: refactor

#55 [feat] #2 issue - 특정 이슈 조회 api 구현
  src/main/java/com/example/IssueTrackingSystem/converter/CommentConverter.java
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/converter/UserConverter.java
  src/main/java/com/example/IssueTrackingSystem/repository/CommentRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/CommentService/CommentCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/CommentService/CommentQueryService.java
  src/main/java/com/example/IssueTrackingSystem/service/CommentService/CommentQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueQueryService.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/IssueController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Comment/CommentRequestDTO.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Comment/CommentResponseDTO.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueResponseDTO.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/User/UserResponseDTO.java
Labels: feat

#69 [refactor] 이슈 상태, 우선순위 수정 api를 하나의 api로 합치기
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandService.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/IssueController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueRequestDTO.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueResponseDTO.java
Labels: refactor

#73 [refactor] 전체 이슈 조회 api에서 각 이슈마다 priority 추가, 특정 이슈 조회 api에 priority, status 추가
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueResponseDTO.java
Labels: refactor

#75 [refactor] 프로젝트 참여 유저 검색 api 수정사항
  src/main/java/com/example/IssueTrackingSystem/converter/ProjectUserConverter.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/ProjectUserController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/ProjectUser/ProjectUserResponseDTO.java
Labels: refactor

#78 [refactor] admin이 특정 프로젝트에 계정 추가 api에서 db에 userName도 저장
  src/main/java/com/example/IssueTrackingSystem/domain/entity/mapping/ProjectUser.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandServiceImpl.java
Labels: refactor

#83 [refactor] 담당자 지정 및 삭제 admin계정도 가능하게 하는 기능 구현
  src/main/java/com/example/IssueTrackingSystem/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandServiceImpl.java
Labels: refactor

#84 [feat] #1 Project - 로그인된 유저가 참여중인 프로젝트 조회 기능 API 구현
  src/main/java/com/example/IssueTrackingSystem/converter/ProjectUserConverter.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/mapping/ProjectUser.java
  src/main/java/com/example/IssueTrackingSystem/repository/ProjectUserRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectUserService/ProjectUserQueryService.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectUserService/ProjectUserQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/ProjectUserController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/ProjectUser/ProjectUserResponseDTO.java
Labels: feat

#86 [refactor] 특정이슈 조회하는 api의 Response Body의 comments에 createdAt 추가
  src/main/java/com/example/IssueTrackingSystem/converter/CommentConverter.java
  src/main/java/com/example/IssueTrackingSystem/repository/CommentRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/CommentService/CommentQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Comment/CommentResponseDTO.java
Labels: refactor

#92 [refactor] 프로젝트, 이슈 삭제 시 cascade 적용
  src/main/java/com/example/IssueTrackingSystem/domain/entity/Issue.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/Project.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/User.java
Labels: refactor

#97 [refactor] 로그인 api의 response body에 userName, Name추가
  src/main/java/com/example/IssueTrackingSystem/converter/UserConverter.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/User/UserResponseDTO.java
Labels: refactor

#102 [refractor] 프로젝트 참여 유저 검색에서 username 뿐만 아닌 name도 받아오게 수정
  src/main/java/com/example/IssueTrackingSystem/converter/ProjectUserConverter.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/ProjectUser/ProjectUserResponseDTO.java
Labels: refactor

#103 [feat] #2 issue - 이슈 통계 분석 api
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/domain/common/BaseEntity.java
  src/main/java/com/example/IssueTrackingSystem/repository/IssueRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueQueryService.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectQueryService.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectUserService/ProjectUserQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/UserService/UserCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/service/UserService/UserQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/IssueController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueRequestDTO.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Issue/IssueResponseDTO.java
Labels: feat

#107 [feat] #2 issue - 유저가 본인이 assignee로 돼있는 이슈 리스트 조회
  src/main/java/com/example/IssueTrackingSystem/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/Issue.java
  src/main/java/com/example/IssueTrackingSystem/repository/IssueRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueQueryService.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueQueryServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/IssueController.java
Labels: feat

#109 [refactor] assignee된 사람만 fixer가 될 수 있는 권한 부여(fixer지정, 삭제api에 추가), admin에도 권한 부여
  src/main/java/com/example/IssueTrackingSystem/converter/IssueConverter.java
  src/main/java/com/example/IssueTrackingSystem/service/IssueService/IssueCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/IssueController.java
Labels: refactor

#110 [feat] implement statistics
  src/main/java/com/example/IssueTrackingSystem/web/controller/PageController.java
  src/main/resources/static/javascript/issue.js
  src/main/resources/static/javascript/issue_member.js
  src/main/resources/static/javascript/nav.js
  src/main/resources/static/javascript/statistics.js
  src/main/resources/static/style/issue.css
  src/main/resources/static/style/navbar.css
  src/main/resources/static/style/statistics.css
  src/main/resources/templates/issue.html
  src/main/resources/templates/statistics.html
Labels: feat

#115 [refactor] refine detail ui design
  src/main/resources/static/javascript/statistics.js
  src/main/resources/static/style/index.css
  src/main/resources/templates/index.html
  src/main/resources/templates/statistics.html
Labels: refactor

#117 [fix] search
  src/main/resources/static/javascript/issue.js
Labels: bug

#118 [feat] #1 Project - 프로젝트 내에서 계정 삭제
  src/main/java/com/example/IssueTrackingSystem/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/IssueTrackingSystem/domain/entity/Project.java
  src/main/java/com/example/IssueTrackingSystem/repository/ProjectUserRepository.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandService.java
  src/main/java/com/example/IssueTrackingSystem/service/ProjectService/ProjectCommandServiceImpl.java
  src/main/java/com/example/IssueTrackingSystem/web/controller/ProjectController.java
  src/main/java/com/example/IssueTrackingSystem/web/dto/Project/ProjectRequestDTO.java
Labels: feat

#122 [feat] show project as card
  src/main/resources/static/javascript/project.js
  src/main/resources/static/style/project.css
Labels: feat
